### ISSUE TITLE
Unable to find settings. D&D 4.0.2

### ISSUE THREAD

**Issue by Maxusgamer** [misthero/dnd5e-spellpoints#106]
The module is currently enabled, the item is there in the compendium, but the settings don't pop up in the menu.

I already disabled all modules, tried it in a blank test world, and reinstalled, but it keeps persisting.
Attached images showing errors and proof:
![newimage](https://github.com/user-attachments/assets/6a12a9bc-0383-48e2-b019-846aafe4adc0)
![newerimage](https://github.com/user-attachments/assets/616fd606-516c-4f8a-9988-059b8ed7fe11)

**Comment by misthero** [comment]
Thx for reporting but I'm not able to reproduce, I've also tried to reproduce your setup with the modules you have enabled in your screenshots. 

![immagine](https://github.com/user-attachments/assets/7e665572-b60f-4e37-b831-15a64b20b070)

also I cannot see the error you got in your console screen also in the screen I cannot see the module causing it.

usually when you get a warning or an error, somewhere in the error stack is possible to see the file name where the error originated in the file list, for example with those modules enabled i see some warning showing the module causing it:

![immagine](https://github.com/user-attachments/assets/8ebbde2f-7fbf-4e1a-b7e0-7428b0ee1115)

anyway I need some more details to find the error. Are you on foundry v12.331?
What browser are you using?

**Comment by Maxusgamer** [comment]
Yes, I am currently running on Foundry version 12 build 331, using Firefox as the browser, and the game is being hosted by The Forge.

**Comment by Maxusgamer** [comment]
Update, I have tried it on another Browser too: Chrome, and the problem is still the same.

**Comment by misthero** [comment]
I don't see this error being related with "dnd5e-spellpoints" module. 

`Failed to execute 'define' on 'CustomElementRegistry': the name "copyable-text"` means that somewhere in the code there are 2 reference to the same thing, it usually happens when you have something like this:
```
require("copyable-text");
require("somefolder/copyable-text");
```

Are you sure that if you create a new world with just the spellpoints module enabled it doesn't work?

**Comment by Maxusgamer** [comment]
I have, and I have even done it again, but the settings just don't want to appear.
![awdawimage](https://github.com/user-attachments/assets/b3059a80-958b-4241-878e-4a0e7549b0d7)

**Comment by misthero** [comment]
So, I checked with foundry support and other devs, the issue you are experimenting doesn't look is comingi from the spellpoints module and could be something specific on the forge. I do not have a forge account where to test it anyway. I wonder why only the spellpoints module settings do not appear...

**Comment by Maxusgamer** [comment]
I have no idea either. I tried to login to the server a few times, even stopped it and restarted it, but nothing seems to work.

**Comment by misthero** [comment]
Just to confirm or exclude the forge being the issue here, are could you try to setup a local foundry on your machine, cloning your world in it and check if the issue persist there? I cannot find someone to try it on the forge.

**Comment by Maxusgamer** [comment]
Then it indeed seems to be the forge, as when I load the game on my own pc, the settings appear.
![imaaaaaage](https://github.com/user-attachments/assets/14e19535-30c2-46ba-bd7b-cf6256ace66d)

**Comment by misthero** [comment]
thanks for taking your time checking it. You should try asking the forge support for help.

those errors looks like are coming from them, anyway I don't like that my module settings are not functioning on the forge so if they say I should do something to workaround that issue I'd like to know. So I'll be grateful if you could report me if they need me to make some changes to the module.

meanwhile I sent them an email requesting a developer account on the forge to test my modules, since I've read that should be possible. Hope it's true and fast. 

thank you.

let me know if you get an answer from them

**Comment by rikmarais** [comment]
Hi there @misthero

I believe the issue is stemming from a double import of the dnd5e system file here to https://github.com/misthero/dnd5e-spellpoints/blob/9567b6df348acedf814b2c70e0501ff0bc078efb/scripts/main.js#L1

Since it's a relative import, when dnd5e-spellpoints is installed via the Forge Bazaar the relative path will point to the path of the dnd5e system file on the Bazaar, rather than from the root of the file structure. This leads to a double import of the dnd5e.mjs file, which is where that error referenced in the image here https://github.com/misthero/dnd5e-spellpoints/issues/106#issuecomment-2366107781 comes from.

Would it be possible to change that line from relative path import
```
import { DND5E } from "../../../systems/dnd5e/dnd5e.mjs";
```
to an absolute path import?
```
import { DND5E } from "/systems/dnd5e/dnd5e.mjs";
```
I believe that keeps functionality the same but will avoid the double import.
The Forge should get back to your email soon with a dev account for testing!

**Comment by misthero** [comment]
Oh, great! Thank you. I probably would never have guessed that. I'll test the code and push an update as soon as possible.

**Comment by misthero** [comment]
Ok, new release is ready: https://github.com/misthero/dnd5e-spellpoints/releases/tag/v2.4.21

will soon appear on foundry.

The import was relative since is perfectly possible to have foundry in a subfolder, anyway I have worked around it so no import is necessary anymore.

I still cannot test on The Forge, but this way it should work regardless.

**Comment by Maxusgamer** [comment]
Thank you so much for the swift work! I just tested it on the forge, and the settings are there!
![sdeaWEW](https://github.com/user-attachments/assets/42616467-4f7e-4c4b-8083-d3721dc29a6d)
