### ISSUE TITLE
Spell points active, extra step to enable in configure game settings.

### ISSUE THREAD

**Issue by DrunkenSage** [misthero/dnd5e-spellpoints#108]
foundry v12 331
dnd 5e v4.0.3
spell points v2.4.21

Nothing serious to mention, Just figured I'd drop this in to help.

When adding the module, reset server to apply and it appears as active under module management. At this state everything looks like its up and running, but after adding the spell points it doesn't update the resources after spell use or spell point bar underneath the hp hit die.

I had to go into configure settings, select the Spell points system and then enable it. It does successfully work and apply all visuals and resource use after this. Maybe a mention in the set up instructions to double check this configure game settings section to ensure everything works as it should.
![image](https://github.com/user-attachments/assets/2679fd3a-9580-4522-b3fd-9dce6c6db718)

Thanks for the module!
Cheers!

**Comment by misthero** [comment]
oh yes, you are right, thank you for reminding it to me, I have to remove that setting... and the code bound to that setting.

that is a leftover from the version where spellpoints module was using the actor's resurces. There is no real need for it since now only actors with the item can use spellpoints.

It is confusing now, I will remove it.

**Comment by misthero** [comment]
https://github.com/misthero/dnd5e-spellpoints/releases/tag/v2.4.22

latest version has old settings removed
