### ISSUE TITLE
(BUG) 9.X Module doesn't compute spell points anymore

### ISSUE THREAD

**Issue by marcottedan** [misthero/dnd5e-spellpoints#21]
In 9.X, it says that spell points will be consumed but fails to find the right resources and substract the amount of spell points used. There's no stack traces in the logs though.

**Comment by misthero** [comment]
thx  for reporting this, I'll look into this as soon as I can, this module is not yet declared compatible with 9.x anyway.

**Comment by misthero** [comment]
@kyleady 
this is due to the fact that withActorData function is returning undefined.

`/**
   * Evaluates the given formula with the given actors data. Uses FoundryVTT's Roll
   * to make this evaluation.
   * @param {string|number} formula The rollable formula to evaluate.
   * @param {object} actor The actor used for variables.
   * @return {number} The result of the formula.
   */
  static withActorData(formula, actor) {
    let r = new Roll('(' + formula + ')', actor.data.data);
    r.evaluate();
    console.log('ROLL',r);
    console.log('ROLL.result',r.result);
    console.log('ROLL.total',r.total); //undefined
    return r.total;
  }`

**Comment by MrVauxs** [comment]
Any progress on this? Applying kyleady's fix works, only issue is this has to be done manually as the changes haven't been pushed to a new version yet.

**Comment by misthero** [comment]
Patch is now published you can update directly from foundry
