### ISSUE TITLE
dnd5e 1.2.0 + Better Rolls for 5e Incompatibility

### ISSUE THREAD

**Issue by MrVauxs** [misthero/dnd5e-spellpoints#4]
Upon clicking any spell that consumes spell slots results in the spell not being cast, points not being deducted, and the following error.
![image](https://user-images.githubusercontent.com/32039708/101877803-de8b5480-3b8e-11eb-83bd-158f61fd75a7.png)

I couldn't find any methods that had to be updated before updating to the new system version, but alas, I was wrong.

**Comment by misthero** [comment]
thankyou for the heads up, I'll check this.

**Comment by misthero** [comment]
ok I've had the chanche to try it and the module looks like it works, or I cannot find what the issue is.
Can you help me a little more? I need to know:
 what options you have checked in this module?
 what kind of spellcaster is casting?
happend with every spell?

last but not the least, can you try running once "find the cuplrit"? ( https://github.com/Moerill/fvtt-find-the-culprit )

**Comment by MrVauxs** [comment]
The Culprit: 
![image](https://user-images.githubusercontent.com/32039708/101967158-d7118d00-3c1a-11eb-9000-10cc1ebfd470.png)

Settings:
![image](https://user-images.githubusercontent.com/32039708/101967510-0922ef00-3c1b-11eb-811c-169834546a3a.png)

**Comment by misthero** [comment]
problem is better rolls is not compatible with dnd5e 1.2.0
here is a temporary fix if you feel confidend doing modifications yourself
`lvl = spellFormData.level;
consume = Boolean(spellFormData.consumeSlot);
placeTemplate = Boolean(spellFormData.placeTemplate);`

**Comment by MrVauxs** [comment]
The fix indeed works and I see it has already been implemented in a [pull request](https://github.com/RedReign/FoundryVTT-BetterRolls5e/pull/176) for the module.
Thanks!
